import pkg from './package.json';

export default defineNuxtConfig({
    runtimeConfig: {
        public: {
            version: pkg.version,
        },
    },
    app: {
        head: {
            meta: [
                {
                    name: 'viewport',
                    content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no',
                },
            ],
            // The 11C mark, mark only — a wordmark is unreadable in a tab strip.
            // Declared rather than left to the implicit /favicon.ico lookup, so
            // the SVG is offered first: it is the one format that can follow the
            // viewer's colour scheme, and browsers that understand it prefer it.
            // The .ico is the fallback for those that do not (Safari), and
            // apple-touch-icon is what iOS uses when a page is added to a home
            // screen. All three are generated by scripts/build-favicons.sh.
            link: [
                { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
                { rel: 'icon', type: 'image/x-icon', sizes: '16x16 32x32 48x48 64x64', href: '/favicon.ico' },
                { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
            ],
        },
    },
    nitro: {
        experimental: {
            websocket: true,
        },
    },
    css: ['~/scss/tokens-root.scss'],
    compatibilityDate: '2026-01-01',
    devtools: { enabled: true },
    modules: [
        '@nuxt/eslint',
        '@nuxt/devtools',
        '@pinia/nuxt',
        '@nuxt/image',
        '@nuxt/icon',
        '@nuxt/fonts',
        '@nuxt/scripts',
    ],
    devServer: {
        port: 8080,
    },
    typescript: {
        typeCheck: 'build',
    },
    vite: {
        define: {
            global: 'globalThis',
        },
        css: {
            preprocessorMaxWorkers: true,
            preprocessorOptions: {
                scss: {
                    additionalData: `@use "~/scss/colors.scss" as *;@use "~/scss/variables.scss" as *;@use "~/scss/tokens.scss" as *;`,
                },
            },
        },
        resolve: {
            alias: {
                '.prisma/client/index-browser': './node_modules/.prisma/client/index-browser.js',
            },
        },
    },
});
