import pkg from './package.json';
import { CSRF_COOKIE, CSRF_HEADER } from './shared/csrf';

/**
 * Double-submit CSRF (issue #81): echoes the `CSRF_COOKIE` value back as the
 * `CSRF_HEADER` on every state-changing same-origin request, so no existing
 * `$fetch`/`useRequestFetch()` call site across `app/` has to change.
 *
 * This is a classic inline `<script>`, not a Nuxt plugin — see the long
 * comment in `shared/csrf.ts` for why a plugin's `setup()` runs too late to
 * intercept `fetch`: Nuxt's own `$fetch` singleton captures `globalThis.fetch`
 * once, at MODULE EVALUATION time (`#build/fetch.mjs`), which always finishes
 * before any plugin callback runs. A non-module script tag, by contrast,
 * executes during HTML parsing — strictly before any deferred `type="module"`
 * script, regardless of position in the document — so patching `window.fetch`
 * here is the only place guaranteed to win the race. Safe under this app's CSP
 * (`script-src ... 'unsafe-inline'`, `security-headers.ts`), so it needs no
 * nonce.
 */
const csrfFetchPatchScript = `(function () {
  var COOKIE = ${JSON.stringify(CSRF_COOKIE)};
  var HEADER = ${JSON.stringify(CSRF_HEADER)};
  var STATE_CHANGING = { POST: 1, PUT: 1, PATCH: 1, DELETE: 1 };
  var nativeFetch = window.fetch.bind(window);

  function csrfToken() {
    var match = document.cookie.match(new RegExp('(?:^|; )' + COOKIE + '=([^;]*)'));
    return match ? decodeURIComponent(match[1]) : null;
  }

  function isSameOrigin(input) {
    try {
      var raw = typeof input === 'string' ? input : input.url;
      return new URL(raw, window.location.href).origin === window.location.origin;
    } catch (e) {
      return false;
    }
  }

  window.fetch = function (input, init) {
    var method = ((init && init.method) || (typeof input === 'object' && input.method) || 'GET').toUpperCase();

    if (STATE_CHANGING[method] && isSameOrigin(input)) {
      var token = csrfToken();

      if (token) {
        var headers = new Headers((init && init.headers) || (typeof input === 'object' && input.headers) || undefined);
        headers.set(HEADER, token);
        init = Object.assign({}, init, { headers: headers });
      }
    }

    return nativeFetch(input, init);
  };
})();`;

export default defineNuxtConfig({
    runtimeConfig: {
        // Cloudflare Turnstile secret key (issue #79) — server-only, read
        // directly from process.env by server/utils/turnstile.ts, declared
        // here too so it is documented and typed like every other server
        // secret. PRODUCTION MUST SET A REAL SECRET; left unset, login skips
        // the CAPTCHA requirement entirely and relies on the rate limit
        // alone — see turnstile.ts's own comment.
        turnstileSecretKey: process.env.TURNSTILE_SECRET_KEY ?? '',
        public: {
            version: pkg.version,
            // Public Turnstile site key — safe to ship to the client.
            // Defaults to Cloudflare's published always-pass TEST key so
            // local dev renders a working widget with zero configuration.
            turnstileSiteKey: process.env.TURNSTILE_SITE_KEY ?? '1x00000000000000000000AA',
        },
    },
    app: {
        head: {
            meta: [
                {
                    name: 'viewport',
                    content: 'width=device-width, initial-scale=1.0',
                },
            ],
            // The 11C mark, mark only — a wordmark is unreadable in a tab strip.
            // Declared rather than left to the implicit /favicon.ico lookup, so
            // the SVG is offered first: it is the one format that can follow the
            // viewer's colour scheme, and browsers that understand it prefer it.
            // The .ico is the fallback for those that do not (Safari), and
            // apple-touch-icon is what iOS uses when a page is added to a home
            // screen. All three are generated by scripts/build-favicons.sh.
            link: [
                { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
                { rel: 'icon', type: 'image/x-icon', sizes: '16x16 32x32 48x48 64x64', href: '/favicon.ico' },
                { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
            ],
            script: [
                // See csrfFetchPatchScript above for why this has to be a raw
                // script tag rather than a plugin.
                { key: 'csrf-fetch-patch', innerHTML: csrfFetchPatchScript },
            ],
        },
    },
    nitro: {
        experimental: {
            websocket: true,
            openAPI: true,
        },
        openAPI: {
            meta: {
                title: "Calendry API",
                version: "0.0.1-beta",
            }
        },
        alias: {
            // See server/utils/pgNativeStub.ts — pg's optional native addon,
            // never installed, needs somewhere to resolve at build time.
            'pg-native': './server/utils/pgNativeStub.ts',
        },
    },
    css: ['~/scss/tokens-root.scss'],
    compatibilityDate: '2026-01-01',
    devtools: { enabled: false },
    modules: [
        '@nuxt/eslint',
        '@nuxt/devtools',
        '@pinia/nuxt',
        '@nuxt/image',
        '@nuxt/icon',
        '@nuxt/fonts',
        '@nuxt/scripts',
    ],
    devServer: {
        port: 8080,
    },
    typescript: {
        typeCheck: 'build',
    },
    vite: {
        define: {
            global: 'globalThis',
        },
        css: {
            preprocessorMaxWorkers: true,
            preprocessorOptions: {
                scss: {
                    additionalData: `@use "~/scss/colors.scss" as *;@use "~/scss/variables.scss" as *;@use "~/scss/tokens.scss" as *;`,
                },
            },
        },
        resolve: {
            alias: {
                '.prisma/client/index-browser': './node_modules/.prisma/client/index-browser.js',
            },
        },
    },
});
